export const DAW_CONTROL__PLAY = 'DAWControl/PLAY';
export const DAW_CONTROL__PAUSE = 'DAWControl/PAUSE';
export const DAW_CONTROL__BACKWARD = 'DAWControl/BACKWARD';

export const DAW_CONTROL__SET_SOLO = 'DAWControl/SET_SOLO';
export const DAW_CONTROL__SET_MUTE = 'DAWControl/SET_MUTE';

export const DAW_CONTROL__SET_DATA = 'DAWControl/SET_DATA';
export const DAW_CONTROL__SET_CURRENT_TIME = 'DAWControl/SET_CURRENT_TIME';
export const DAW_CONTROL__SET_CURRENT_SCROLL_LEFT = 'DAWControl/SET_CURRENT_SCROLL_LEFT';

export const DAW_CONTROL__SET_ACTIVE_SESSION = 'DAWControl/DAW_CONTROL__SET_ACTIVE_SESSION';
export const DAW_CONTROL__SET_ACTIVE_SESSIONS = 'DAWControl/DAW_CONTROL__SET_ACTIVE_SESSIONS';

export const DAW_CONTROL__SET_ACTION_SESSION__IS_MUTE_STATE = 'DAWControl/DAW_CONTROL__SET_ACTION_SESSION__IS_MUTE_STATE';
export const DAW_CONTROL__SET_ACTION_SESSION__IS_SOLO_STATE = 'DAWControl/DAW_CONTROL__SET_ACTION_SESSION__IS_SOLO_STATE';

export const DAW_CONTROL__SET_ACTIVE_SESSION_DATA = 'DawControl/DAW_CONTROL__SET_ACTIVE_SESSION_DATA';
export const DAW_CONTROL__UPDATE_ACTIVE_SESSION_DATA = 'DawControl/DAW_CONTROL__UPDATE_ACTIVE_SESSION_DATA';