export const DAW_CONTROL__PLAY = 'DAWControl/PLAY';
export const DAW_CONTROL__PAUSE = 'DAWControl/PAUSE';
export const DAW_CONTROL__BACKWARD = 'DAWControl/BACKWARD';

export const DAW_CONTROL__SET_DATA = 'DAWControl/SET_DATA';
export const DAW_CONTROL__SET_CURRENT_TIME = 'DAWControl/SET_CURRENT_TIME';
export const DAW_CONTROL__SET_CURRENT_SCROLL_LEFT = 'DAWControl/SET_CURRENT_SCROLL_LEFT';